name: plankton-classification-scivision-full
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - anyio=3.7.0
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asciitree=0.3.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.10
  - aws-c-io=0.13.27
  - aws-c-mqtt=0.8.13
  - aws-c-s3=0.3.12
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.2
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blosc=1.21.4
  - bokeh=3.2.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.0
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charls=2.4.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - comm=0.1.3
  - contourpy=1.1.0
  - cryptography=41.0.1
  - curl=8.1.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.6.1
  - dask-core=2023.6.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.6.1
  - entrypoints=0.4
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - exifread=3.0.0
  - fasteners=0.17.3
  - flit-core=3.9.0
  - fonttools=4.40.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - glog=0.6.0
  - gst-plugins-base=1.22.4
  - gstreamer=1.22.4
  - hdf4=4.2.15
  - hdf5=1.14.1
  - icu=72.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.1
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - intake=0.6.6
  - intake-xarray=0.6.1
  - ipykernel=6.23.3
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.7
  - jedi=0.18.2
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.3.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.1
  - jupyter_events=0.6.3
  - jupyter_server=2.7.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.8
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarrow=12.0.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.55.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=4.23.2
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libthrift=0.18.1
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=16.0.6
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.6.0
  - nbconvert-core=7.6.0
  - nbconvert-pandoc=7.6.0
  - nbformat=5.9.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - netcdf4=1.6.4
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numcodecs=0.11.0
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.1.1
  - orc=1.8.4
  - overrides=7.3.1
  - packaging=23.1
  - pandas=1.5.3
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.0
  - ply=3.11
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pycparser=2.21
  - pygments=2.15.1
  - pyobjc-core=9.2
  - pyobjc-framework-cocoa=9.2
  - pyopenssl=23.2.0
  - pyparsing=3.1.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - re2=2023.03.02
  - readline=8.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.19.3
  - scipy=1.10.0
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.9
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - tblib=1.7.0
  - terminado=0.17.1
  - tifffile=2023.7.4
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.40.0
  - widgetsnbextension=4.0.8
  - xarray=2023.6.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.15.0
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.15.0
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
      - distinctipy==1.2.2
      - matplotlib==3.7.1
      - pooch==1.6.0
      - pydantic==1.10.11
      - torch==1.10.0
      - torchvision==0.11.1
      - scivision==0.7.0

